language: node_js
node_js:
    - 14.15
before_script:
    - cd testApp && npm i && cp .env-example .env
    - npm install -g codecov
script:
    - npm run test:cov && codecov
branches:
    only:
        - master
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
