name: build
on: [push, pull_request]
# on:
# push:
#   branches:
#     - master
#     - 'v*.*.*'
jobs:
  run-tests:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18.x", "20.x", "22.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: cd test && npm i && cp .env-example .env && cd ..
      - run: cd docs && yarn install && npm run build && cd ..
      - run: npm i -g yarn
      - run: yarn install
      - run: npm run test:cov
      - name: Codecov
        uses: codecov/codecov-action@v5.4.0
