name: tests
on: [push, pull_request]
# on:
  # push:
  #   branches:
  #     - master
  #     - 'v*.*.*'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd test && npm i && cp .env-example .env && cd ..
      - run: npm install -g codecov
      - run: cd docs && npm i && npm run build && cd ..
      - run: npm i -g yarn
      - run: yarn install
      - run: npm run test:cov && codecov